# Copyright CPqD All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.kingbeefcattle.com:
    container_name: orderer.kingbeefcattle.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # disabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=false
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/kingbeefcattle.com/orderers/orderer.kingbeefcattle.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/kingbeefcattle.com/orderers/orderer.kingbeefcattle.com/tls/:/var/hyperledger/orderer/tls
    - orderer.kingbeefcattle.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.farm1.kingbeefcattle.com:
    container_name: peer0.farm1.kingbeefcattle.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.farm1.kingbeefcattle.com
      - CORE_PEER_ADDRESS=peer0.farm1.kingbeefcattle.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.farm1.kingbeefcattle.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.farm1.kingbeefcattle.com:7051
      - CORE_PEER_LOCALMSPID=Farm1MSP
    volumes:
        - /var/run/:/host/var/run/
        - $GOPATH/src/github.com/hyperledger/fabric/:/opt/gopath/src/github.com/hyperledger/fabric
        - $GOPATH/src/github.com/gogo/:/opt/gopath/src/github.com/gogo
        - ../crypto-config/peerOrganizations/farm1.kingbeefcattle.com/peers/peer0.farm1.kingbeefcattle.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/farm1.kingbeefcattle.com/peers/peer0.farm1.kingbeefcattle.com/tls:/etc/hyperledger/fabric/tls
        - peer0.farm1.kingbeefcattle.com:/var/hyperledger/production
    ports:
      - 11051:7051
      - 11052:7052
      - 11053:7053

  peer1.farm1.kingbeefcattle.com:
    container_name: peer1.farm1.kingbeefcattle.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.farm1.kingbeefcattle.com
      - CORE_PEER_ADDRESS=peer1.farm1.kingbeefcattle.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.farm1.kingbeefcattle.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.farm1.kingbeefcattle.com:7051
      - CORE_PEER_LOCALMSPID=Farm1MSP
    volumes:
        - /var/run/:/host/var/run/
        - $GOPATH/src/github.com/hyperledger/fabric/:/opt/gopath/src/github.com/hyperledger/fabric
        - $GOPATH/src/github.com/gogo/:/opt/gopath/src/github.com/gogo
        - ../crypto-config/peerOrganizations/farm1.kingbeefcattle.com/peers/peer1.farm1.kingbeefcattle.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/farm1.kingbeefcattle.com/peers/peer1.farm1.kingbeefcattle.com/tls:/etc/hyperledger/fabric/tls
        - peer1.farm1.kingbeefcattle.com:/var/hyperledger/production

    ports:
      - 12051:7051
      - 12052:7052
      - 12053:7053    

  peer0.farm2.kingbeefcattle.com:
    container_name: peer0.farm2.kingbeefcattle.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.farm2.kingbeefcattle.com
      - CORE_PEER_ADDRESS=peer0.farm2.kingbeefcattle.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.farm2.kingbeefcattle.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.farm2.kingbeefcattle.com:7051
      - CORE_PEER_LOCALMSPID=Farm2MSP
    volumes:
        - /var/run/:/host/var/run/
        - $GOPATH/src/github.com/hyperledger/fabric/:/opt/gopath/src/github.com/hyperledger/fabric
        - $GOPATH/src/github.com/gogo/:/opt/gopath/src/github.com/gogo
        - ../crypto-config/peerOrganizations/farm2.kingbeefcattle.com/peers/peer0.farm2.kingbeefcattle.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/farm2.kingbeefcattle.com/peers/peer0.farm2.kingbeefcattle.com/tls:/etc/hyperledger/fabric/tls
        - peer0.farm2.kingbeefcattle.com:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9052:7052
      - 9053:7053

  peer1.farm2.kingbeefcattle.com:
    container_name: peer1.farm2.kingbeefcattle.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.farm2.kingbeefcattle.com
      - CORE_PEER_ADDRESS=peer1.farm2.kingbeefcattle.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.farm2.kingbeefcattle.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.farm2.kingbeefcattle.com:7051
      - CORE_PEER_LOCALMSPID=Farm2MSP
    volumes:
        - /var/run/:/host/var/run/
        - $GOPATH/src/github.com/hyperledger/fabric/:/opt/gopath/src/github.com/hyperledger/fabric
        - $GOPATH/src/github.com/gogo/:/opt/gopath/src/github.com/gogo
        - ../crypto-config/peerOrganizations/farm2.kingbeefcattle.com/peers/peer1.farm2.kingbeefcattle.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/farm2.kingbeefcattle.com/peers/peer1.farm2.kingbeefcattle.com/tls:/etc/hyperledger/fabric/tls
        - peer1.farm2.kingbeefcattle.com:/var/hyperledger/production
    ports:
      - 10051:7051
      - 10052:7052
      - 10053:7053

  peer0.slaughterhouse.kingbeefcattle.com:
    container_name: peer0.slaughterhouse.kingbeefcattle.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.slaughterhouse.kingbeefcattle.com
      - CORE_PEER_ADDRESS=peer0.slaughterhouse.kingbeefcattle.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.slaughterhouse.kingbeefcattle.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.slaughterhouse.kingbeefcattle.com:7051
      - CORE_PEER_LOCALMSPID=SlaughterhouseMSP
    volumes:
        - /var/run/:/host/var/run/
        - $GOPATH/src/github.com/hyperledger/fabric/:/opt/gopath/src/github.com/hyperledger/fabric
        - $GOPATH/src/github.com/gogo/:/opt/gopath/src/github.com/gogo
        - ../crypto-config/peerOrganizations/slaughterhouse.kingbeefcattle.com/peers/peer0.slaughterhouse.kingbeefcattle.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/slaughterhouse.kingbeefcattle.com/peers/peer0.slaughterhouse.kingbeefcattle.com/tls:/etc/hyperledger/fabric/tls
        - peer0.slaughterhouse.kingbeefcattle.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7052:7052
      - 7053:7053      

  peer1.slaughterhouse.kingbeefcattle.com:
    container_name: peer1.slaughterhouse.kingbeefcattle.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.slaughterhouse.kingbeefcattle.com
      - CORE_PEER_ADDRESS=peer1.slaughterhouse.kingbeefcattle.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.slaughterhouse.kingbeefcattle.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.slaughterhouse.kingbeefcattle.com:7051
      - CORE_PEER_LOCALMSPID=SlaughterhouseMSP
    volumes:
        - /var/run/:/host/var/run/
        - $GOPATH/src/github.com/hyperledger/fabric/:/opt/gopath/src/github.com/hyperledger/fabric
        - $GOPATH/src/github.com/gogo/:/opt/gopath/src/github.com/gogo
        - ../crypto-config/peerOrganizations/slaughterhouse.kingbeefcattle.com/peers/peer1.slaughterhouse.kingbeefcattle.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/slaughterhouse.kingbeefcattle.com/peers/peer1.slaughterhouse.kingbeefcattle.com/tls:/etc/hyperledger/fabric/tls
        - peer1.slaughterhouse.kingbeefcattle.com:/var/hyperledger/production

    ports:
      - 8051:7051
      - 8052:7052
      - 8053:7053

  peer0.supermarket1.kingbeefcattle.com:
    container_name: peer0.supermarket1.kingbeefcattle.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.supermarket1.kingbeefcattle.com
      - CORE_PEER_ADDRESS=peer0.supermarket1.kingbeefcattle.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.supermarket1.kingbeefcattle.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.supermarket1.kingbeefcattle.com:7051
      - CORE_PEER_LOCALMSPID=Supermarket1MSP
    volumes:
        - /var/run/:/host/var/run/
        - $GOPATH/src/github.com/hyperledger/fabric/:/opt/gopath/src/github.com/hyperledger/fabric
        - $GOPATH/src/github.com/gogo/:/opt/gopath/src/github.com/gogo
        - ../crypto-config/peerOrganizations/supermarket1.kingbeefcattle.com/peers/peer0.supermarket1.kingbeefcattle.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/supermarket1.kingbeefcattle.com/peers/peer0.supermarket1.kingbeefcattle.com/tls:/etc/hyperledger/fabric/tls
        - peer0.supermarket1.kingbeefcattle.com:/var/hyperledger/production
    ports:
      - 13051:7051
      - 13052:7052
      - 13053:7053

  peer1.supermarket1.kingbeefcattle.com:
    container_name: peer1.supermarket1.kingbeefcattle.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.supermarket1.kingbeefcattle.com
      - CORE_PEER_ADDRESS=peer1.supermarket1.kingbeefcattle.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.supermarket1.kingbeefcattle.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.supermarket1.kingbeefcattle.com:7051
      - CORE_PEER_LOCALMSPID=Supermarket1MSP
    volumes:
        - /var/run/:/host/var/run/
        - $GOPATH/src/github.com/hyperledger/fabric/:/opt/gopath/src/github.com/hyperledger/fabric
        - $GOPATH/src/github.com/gogo/:/opt/gopath/src/github.com/gogo
        - ../crypto-config/peerOrganizations/supermarket1.kingbeefcattle.com/peers/peer1.supermarket1.kingbeefcattle.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/supermarket1.kingbeefcattle.com/peers/peer1.supermarket1.kingbeefcattle.com/tls:/etc/hyperledger/fabric/tls
        - peer1.supermarket1.kingbeefcattle.com:/var/hyperledger/production

    ports:
      - 14051:7051
      - 14052:7052
      - 14053:7053

  peer0.inspection1.kingbeefcattle.com:
    container_name: peer0.inspection1.kingbeefcattle.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.inspection1.kingbeefcattle.com
      - CORE_PEER_ADDRESS=peer0.inspection1.kingbeefcattle.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.inspection1.kingbeefcattle.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.inspection1.kingbeefcattle.com:7051
      - CORE_PEER_LOCALMSPID=Inspection1MSP
    volumes:
        - /var/run/:/host/var/run/
        - $GOPATH/src/github.com/hyperledger/fabric/:/opt/gopath/src/github.com/hyperledger/fabric
        - $GOPATH/src/github.com/gogo/:/opt/gopath/src/github.com/gogo
        - ../crypto-config/peerOrganizations/inspection1.kingbeefcattle.com/peers/peer0.inspection1.kingbeefcattle.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/inspection1.kingbeefcattle.com/peers/peer0.inspection1.kingbeefcattle.com/tls:/etc/hyperledger/fabric/tls
        - peer0.inspection1.kingbeefcattle.com:/var/hyperledger/production
    ports:
      - 15051:7051
      - 15052:7052
      - 15053:7053

  peer1.inspection1.kingbeefcattle.com:
    container_name: peer1.inspection1.kingbeefcattle.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.inspection1.kingbeefcattle.com
      - CORE_PEER_ADDRESS=peer1.inspection1.kingbeefcattle.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.inspection1.kingbeefcattle.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.inspection1.kingbeefcattle.com:7051
      - CORE_PEER_LOCALMSPID=Inspection1MSP
    volumes:
        - /var/run/:/host/var/run/
        - $GOPATH/src/github.com/hyperledger/fabric/:/opt/gopath/src/github.com/hyperledger/fabric
        - $GOPATH/src/github.com/gogo/:/opt/gopath/src/github.com/gogo
        - ../crypto-config/peerOrganizations/inspection1.kingbeefcattle.com/peers/peer1.inspection1.kingbeefcattle.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/inspection1.kingbeefcattle.com/peers/peer1.inspection1.kingbeefcattle.com/tls:/etc/hyperledger/fabric/tls
        - peer1.inspection1.kingbeefcattle.com:/var/hyperledger/production

    ports:
      - 16051:7051
      - 16052:7052
      - 16053:7053

  peer0.inspection2.kingbeefcattle.com:
    container_name: peer0.inspection2.kingbeefcattle.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.inspection2.kingbeefcattle.com
      - CORE_PEER_ADDRESS=peer0.inspection2.kingbeefcattle.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.inspection2.kingbeefcattle.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.inspection2.kingbeefcattle.com:7051
      - CORE_PEER_LOCALMSPID=Inspection2MSP
    volumes:
        - /var/run/:/host/var/run/
        - $GOPATH/src/github.com/hyperledger/fabric/:/opt/gopath/src/github.com/hyperledger/fabric
        - $GOPATH/src/github.com/gogo/:/opt/gopath/src/github.com/gogo
        - ../crypto-config/peerOrganizations/inspection2.kingbeefcattle.com/peers/peer0.inspection2.kingbeefcattle.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/inspection2.kingbeefcattle.com/peers/peer0.inspection2.kingbeefcattle.com/tls:/etc/hyperledger/fabric/tls
        - peer0.inspection2.kingbeefcattle.com:/var/hyperledger/production
    ports:
      - 17051:7051
      - 17052:7052
      - 17053:7053

  peer1.inspection2.kingbeefcattle.com:
    container_name: peer1.inspection2.kingbeefcattle.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.inspection2.kingbeefcattle.com
      - CORE_PEER_ADDRESS=peer1.inspection2.kingbeefcattle.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.inspection2.kingbeefcattle.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.inspection2.kingbeefcattle.com:7051
      - CORE_PEER_LOCALMSPID=Inspection2MSP
    volumes:
        - /var/run/:/host/var/run/
        - $GOPATH/src/github.com/hyperledger/fabric/:/opt/gopath/src/github.com/hyperledger/fabric
        - $GOPATH/src/github.com/gogo/:/opt/gopath/src/github.com/gogo
        - ../crypto-config/peerOrganizations/inspection2.kingbeefcattle.com/peers/peer1.inspection2.kingbeefcattle.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/inspection2.kingbeefcattle.com/peers/peer1.inspection2.kingbeefcattle.com/tls:/etc/hyperledger/fabric/tls
        - peer1.inspection2.kingbeefcattle.com:/var/hyperledger/production

    ports:
      - 18051:7051
      - 18052:7052
      - 18053:7053

