# Copyright 2018 CPqD. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  middleware.go.com:
    build: .
    volumes:
    - ../network/channel-artifacts/:/channel-artifacts/
    - ../network/crypto-config/:/crypto-config/
    - ./go/:/src/
    command: bash -c "go run *.go"
    ports:
      - 7500:7500
    tty: true

networks:
  default:
    external:
      name: network_kingbeefcattle
